server:
  port: 8005
  servlet:
    contextPath: /${spring.application.name}/v1
spring:
  application:
    name: oauth
  mvc:
  pathmatch:
    matching-strategy: ANT_PATH_MATCHER
  cache:
    redis:
    time-to-live: 30000
  
  datasource:
    url: jdbc:mariadb://localhost:3306/sicde?UseUniCode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegancyDatetimeCode=false&serverTimezone=America/Mexico_City
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      max-lifetime: 1800
      idle-timeout: 6000
      connection-timeout: 3000
      auto-commit: false
      maximum-pool-size: 7
      minimum-idle: 10

security:
  jwt:
    secret-key: mamitasClub
    expiration-time: 86400000

user:
  username: 'root'
  password: 'root'
  role: 'ADMIN'
cors:
allowed-origins:
  -http://localhost:4200